version: "3.8"

services:
  hairtime-server:
    build:
      context: ./server
    container_name: hairtime-server
    ports:
      - "3000:3000"
    networks:
      - hairtime-net
    depends_on:
      - postgres

  hairtime-client:
    build:
      context: ./client
      args:
        API_BASE_URL: http://hairtime-server:3000
    container_name: hairtime-client
    ports:
      - "4173:80"
    networks:
      - hairtime-net
    depends_on:
      - hairtime-server

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: natalia
      POSTGRES_PASSWORD: natalia
      POSTGRES_DB: hairtimedb
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - hairtime-net

volumes:
  postgresqldata:

networks:
  hairtime-net:
